language: csharp
solution: Mos6510.sln
install:
  - nuget restore Mos6510.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Mos6510.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Mos6510.Tests/bin/Release/Mos6510.Tests.dll
